title: All about Varin
author: Vdharia
email: vdharz@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A site that describes all about Varin
theme: minima
# social links
twitter_username: varindharia # DO NOT include the @ character, or else the build will fail!
github_username:   PoeticRibbon # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
